### ISSUE TITLE
Browser package

### ISSUE THREAD

**Issue by dderevjanik** [Manwe-777/tool-db#2]
Hello,

would it be possible to also publish a browser-compatible package? It could be much easier to play with tool-db by using script from CDN like https://unpkg.com/tool-db , so It would be possible to just paste script inside your static html file and test tool-db directly from your browser without need to create dummy node project with all libraries (ts, webpack, etc.). 

Btw, really nice project!

**Comment by Manwe-777** [comment]
Hi there!

The code is already compatible with browsers, so it should be relatively easy to set up, also there is an npm package if you use that for development, just `npm install tool-db` (no webpack required)

I'll keep the issue open, I like the idea!

**Comment by dderevjanik** [comment]
Sorry, how can I use `tool-db` without webpack ?

Could you please provide an example?

**Comment by Manwe-777** [comment]
Theres a bunch of ways actually, the easiest and dirtiest is probbaly downloading the compiled files from npm directly, or you can use something like rollup or browserify instead of webpack.. the package is context agnostic.

**Comment by dderevjanik** [comment]
Yeah, I saw several packages bundling "isomorphic" code both for nodejs and browser and publishing directly on npm. 
It would be cool to have tool-db bundled and published to npm, so you can use `unpkg.com` as CDN and then put it into html like `<script src="https://unpkg.com/tool-db@1.4.2/dist/index.js"></script>` or at least have it on other common CDN.

**Comment by Manwe-777** [comment]
The package is already available at npm, except there is no single bundled file, thus you cant use it directly with unpkg yet :)

https://www.npmjs.com/package/tool-db

**Comment by Manwe-777** [comment]
Implemented at f69a4389ad7da9fdf7e10a719cd5d4e522a9a408

Url is [https://unpkg.com/tool-db/bundle.js](https://unpkg.com/tool-db/bundle.js)
