### ISSUE TITLE
Provide Id after initialization

### ISSUE THREAD

**Issue by dderevjanik** [Manwe-777/tool-db#3]
Is there any way to obtain `id` right after initialization (`generatePairKey`)? https://github.com/Manwe-777/tool-db/blob/main/src/tooldb.ts#L279 . Accessing `tooldb.options.id` after initializing `ToolDb` instance returns nothing, because generatePairKey is async action inside constructor.

Possible solutions:
- 👎 Provide callback to constructor method `constructor(options: Partial<ToolDbOptions> = {}, onId: (id) => void)`
- 👎 Provide listener to `ToolDb` -> `onId: (id: string) => void`
- 👍 Provide listener to `ToolDb` -> `onInit: () => void` after which I know that tooldb was initialized (id generated) and I can access `tooldb.options.id`

**Comment by Manwe-777** [comment]
I would go the listener way definitely! I am reluctant of using callbacks whenever possible (you might see only one or two places where I stll use them)

**Comment by Manwe-777** [comment]
Added here: c563d6d104bf899274ac1caf2befd84bb37ad923
